# GitHub Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    # Limit the number of open pull requests
    open-pull-requests-limit: 5
    # Allow both direct updates and security updates
    allow:
      - dependency-type: "all"
    # Group updates by dependency type
    groups:
      microsoft-packages:
        patterns:
          - "Microsoft.*"
          - "System.*"
      testing-packages:
        patterns:
          - "xunit*"
          - "*Test*"
          - "Moq*"
          - "FluentAssertions*"
    # Assign reviewers and labels
    reviewers:
      - "nam20485"
    labels:
      - "dependencies"
      - "automated"
    # Commit message preferences
    commit-message:
      prefix: "deps"
      include: "scope"
    # Ignore certain updates if needed
    ignore:
      # Ignore major version updates for stable packages (can be removed if desired)
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "nam20485"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"