name: "Copilot Setup Steps - Using Devcontainer Prebuild"

# This workflow now uses the prebuild devcontainer image for faster setup
on:
  workflow_dispatch:
# env:
#   DOTNET_VERSION: "9.0.102"
#   NODE_VERSION: "22"
#   POWERSHELL_VERSION: "7.4.x"
#   DEVCONTAINER_IMAGE: "ghcr.io/nam20485/agent-instructions-devcontainer:latest"

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/nam20485/agent-instructions-devcontainer:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # Enhanced permissions for comprehensive development environment setup
      contents: read
      actions: read
      packages: read

    # The devcontainer image already has all tools installed
    # We only need to validate and perform project-specific setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      - name: Setup Script
        run: |
          echo "Running script..."
          ./scripts/copilot-setup-steps.ps1

