namespace GitHubPrTool.Core.Models;

/// <summary>
/// Represents a project kickstart plan generated by AI
/// </summary>
public class ProjectKickstartPlan
{
    /// <summary>
    /// Unique identifier for the plan
    /// </summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Project name
    /// </summary>
    public string ProjectName { get; set; } = string.Empty;

    /// <summary>
    /// Project description
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Technology stack recommendations
    /// </summary>
    public List<string> TechnologyStack { get; set; } = new();

    /// <summary>
    /// Project milestones with timeline
    /// </summary>
    public List<ProjectMilestone> Milestones { get; set; } = new();

    /// <summary>
    /// Recommended team structure
    /// </summary>
    public List<TeamRole> TeamStructure { get; set; } = new();

    /// <summary>
    /// Development phases
    /// </summary>
    public List<DevelopmentPhase> Phases { get; set; } = new();

    /// <summary>
    /// Estimated timeline in weeks
    /// </summary>
    public int EstimatedTimelineWeeks { get; set; }

    /// <summary>
    /// Risk assessments and mitigation strategies
    /// </summary>
    public List<RiskAssessment> Risks { get; set; } = new();

    /// <summary>
    /// Success criteria
    /// </summary>
    public List<string> SuccessCriteria { get; set; } = new();

    /// <summary>
    /// When this plan was generated
    /// </summary>
    public DateTimeOffset GeneratedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// The AI model/version that generated this plan
    /// </summary>
    public string ModelVersion { get; set; } = string.Empty;
}

/// <summary>
/// Represents a project milestone
/// </summary>
public class ProjectMilestone
{
    /// <summary>
    /// Milestone name
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Milestone description
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Deliverables for this milestone
    /// </summary>
    public List<string> Deliverables { get; set; } = new();

    /// <summary>
    /// Estimated duration in weeks
    /// </summary>
    public int DurationWeeks { get; set; }

    /// <summary>
    /// Dependencies on other milestones
    /// </summary>
    public List<string> Dependencies { get; set; } = new();
}

/// <summary>
/// Represents a team role recommendation
/// </summary>
public class TeamRole
{
    /// <summary>
    /// Role title
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Role description and responsibilities
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Required skills
    /// </summary>
    public List<string> RequiredSkills { get; set; } = new();

    /// <summary>
    /// Time commitment (e.g., "Full-time", "Part-time", "Consultant")
    /// </summary>
    public string Commitment { get; set; } = string.Empty;
}

/// <summary>
/// Represents a development phase
/// </summary>
public class DevelopmentPhase
{
    /// <summary>
    /// Phase name
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Phase description
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Key activities in this phase
    /// </summary>
    public List<string> Activities { get; set; } = new();

    /// <summary>
    /// Expected outcomes
    /// </summary>
    public List<string> Outcomes { get; set; } = new();

    /// <summary>
    /// Duration in weeks
    /// </summary>
    public int DurationWeeks { get; set; }
}

/// <summary>
/// Represents a risk assessment
/// </summary>
public class RiskAssessment
{
    /// <summary>
    /// Risk description
    /// </summary>
    public string Risk { get; set; } = string.Empty;

    /// <summary>
    /// Probability (1-5, with 5 being most likely)
    /// </summary>
    public int Probability { get; set; }

    /// <summary>
    /// Impact (1-5, with 5 being highest impact)
    /// </summary>
    public int Impact { get; set; }

    /// <summary>
    /// Mitigation strategies
    /// </summary>
    public List<string> MitigationStrategies { get; set; } = new();
}